trip_trans = TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'Legarda', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'Pureza', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'V.Mapa', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'J.Ruiz', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'Gilmore', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'Betty-Go Belmonte', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'Cubao', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'Anonas', :trip_amount => '25')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'Katipunan', :trip_amount => '25')
             TransportFare.create!(:pickup_location => 'Recto', :drop_location => 'Santolan', :trip_amount => '25')

             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'Katipunan', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'Anonas', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'Cubao', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'Betty-Go Belmonte', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'Gilmore', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'J.Ruiz', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'V.Mapa', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'Pureza', :trip_amount => '25')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'Legarda', :trip_amount => '25')
             TransportFare.create!(:pickup_location => 'Santolan', :drop_location => 'Recto', :trip_amount => '25')
             
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'Recto', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'Pureza', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'V.Mapa', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'J.Ruiz', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'Gilmore', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'Betty-Go Belmonte', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'Cubao', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'Anonas', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'Katipunan', :trip_amount => '25')
             TransportFare.create!(:pickup_location => 'Legarda', :drop_location => 'Santolan', :trip_amount => '25')

             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'Recto', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'Legarda', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'V.Mapa', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'J.Ruiz', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'Gilmore', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'Betty-Go Belmonte', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'Cubao', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'Anonas', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'Katipunan', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Pureza', :drop_location => 'Santolan', :trip_amount => '25')

             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Recto', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Legarda', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Pureza', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'J.Ruiz', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Gilmore', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Betty-GO Belmonte', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Cubao', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Anonas', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Katipunan', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'V.Mapa', :drop_location => 'Santolan', :trip_amount => '25')

             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Recto', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Legarda', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Pureza', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'V.Mapa', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Gilmore', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Betty-Go Belmonte', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Cubao', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Anonas', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Katipunan', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'J.Ruiz', :drop_location => 'Legarda', :trip_amount => '20')

             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'Recto', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'Legarda', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'Pureza', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'V.Mapa', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'J.Ruiz', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'Gilmore', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'Cubao', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'Anonas', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'Katipunan', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Betty-Go Belmonte', :drop_location => 'Legarda', :trip_amount => '20')

             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'Recto', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'Legarda', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'Pureza', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'V.Mapa', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'J.Ruiz', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'Betty-Go Belmonte', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'Cubao', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'Anonas', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'Katipunan', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Gilmore', :drop_location => 'Santolan', :trip_amount => '20')

             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'Recto', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'Legarda', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'Pureza', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'V.Mapa', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'J.Ruiz', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'Gilmore', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'Betty-Go Belmonte', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'Anonas', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'Katipunan', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Cubao', :drop_location => 'Santolan', :trip_amount => '15')

             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'Recto', :trip_amount => '25')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'Legarda', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'Pureza', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'V.Mapa', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'J.Ruiz', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'Gilmore', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'Betty-Go Belmonte', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'Cubao', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'Katipunan', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Anonas', :drop_location => 'Santolan', :trip_amount => '15')
             
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'Recto', :trip_amount => '25')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'Legarda', :trip_amount => '25')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'Pureza', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'V.Mapa', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'J.Ruiz', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'Gilmore', :trip_amount => '20')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'Betty-Go Belmonte', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'Cubao', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'Anonas', :trip_amount => '15')
             TransportFare.create!(:pickup_location => 'Katipunan', :drop_location => 'Santolan', :trip_amount => '15')

             